# Generated by Django 4.0.6 on 2022-07-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_card_options_alter_cardtype_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
