# Generated by Django 4.0.6 on 2022-07-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cardtype',
            options={},
        ),
    ]
