# Generated by Django 4.0.6 on 2022-07-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_card_options_alter_cardtype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карта', 'verbose_name_plural': 'Карты'},
        ),
        migrations.AlterModelOptions(
            name='cardtype',
            options={'verbose_name': 'Тип карты', 'verbose_name_plural': 'Типы карт'},
        ),
    ]
