# Generated by Django 4.0.6 on 2022-07-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_card_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карта', 'verbose_name_plural': 'Карты'},
        ),
    ]
